### ISSUE TITLE
Feature request: autosave workspace

### ISSUE THREAD

**Issue by Marc-JB** [jenius-apps/nightingale-rest-api-client#13]
Add an autosave option, so that I don't lose my new or modified requests and collections when I close the app and forgot to save.

**Comment by dpaulino** [comment]
Thanks for the feedback. I apologize for the inconvenience this may have caused you. I'm putting this on my backlog with high priority. I'll let you know when I have more updates.

**Comment by dpaulino** [comment]
I'm fixing this issue as we speak. Hope to deploy the fix in a day or two. Thanks for everyone's patience

**Comment by dpaulino** [comment]
The fix is rolling out to preview members over the next 24 hours. I report back once it's available to the public.

**Comment by dpaulino** [comment]
I should specify that I am mitigating this issue by providing an option to save your data upon closing the app. This is not exactly "autosaving" because autosaving will require a bit more work. Thus, I am adding this stop gap for now until I can properly implement auto saving.

If any of you are in the preview program, let me know your thoughts once the v3.0.25 update rolls out to you.

**Comment by dpaulino** [comment]
I received feedback from some preview members and they hate the UX of the pop up. Thus, I spent the past few hours fully implementing auto save with an option to disable this in settings. 

I'll report back once this is released to preview members.

**Comment by dpaulino** [comment]
Now rolling out to preview members
