### ISSUE TITLE
Bug: GET requests doesn't send request body

### ISSUE THREAD

**Issue by Demelor** [jenius-apps/nightingale-rest-api-client#16]
It may seem strange to send body with GET requests but it is actually supported by HTTP standard and actively used by Elasticsearch (https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-body.html).

What you expect to happen:
Called server receives GET request body.

What actually happens:
Body is empty on received GET requests.

Reproduction steps:
Create new GET request, select Body tab, then JSON, input request body and press Send.

**Comment by dpaulino** [comment]
Thanks for your feedback, I'll look into this asap!

**Comment by dpaulino** [comment]
Small update: Nightingale uses RestSharp for some of its calls. It seems that RestSharp does not support adding a body to a GET request: https://github.com/restsharp/RestSharp/issues/1330

However, HttpClient in .NET Core does support having a body in GET requests. So it may be possible to add this capability into Nightingale, but it will take more time than I originally thought. I'll report back when I get some time to add this.

**Comment by gvkempen** [comment]
Whilst it would be fun if the app would support GET with body, it is _not_ officially part of the HTTP specification: "The GET method means retrieve whatever information (in the form of an entity) is identified by the Request-URI." (https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html#sec9) Mozilla MDN also informs us that GET requests should not have a body.

Elasticsearch knows GET with body is not standard, and therefore also allows POST requests: "Both HTTP GET and HTTP POST can be used to execute search with body. Since not all clients support GET with body, POST is allowed as well." (quote from the link you provided). So in order to work around this missing feature (and build an app that is in accordance to the HTTP standard), you could just use POST instead of GET.

**Comment by dpaulino** [comment]
Thanks for that information. I also read that sending a body with GET was not standard, so I wasn't too sure if I should be supporting it to let customers work with Elastic Search.

But since Elastic Search can accept POST calls, I will close this issue.
