### ISSUE TITLE
Feature request: show response time in Log

### ISSUE THREAD

**Issue by jburman** [jenius-apps/nightingale-rest-api-client#17]
Would be useful to display the response time in Log window (so don't need to click on the response icon each time)

**Comment by dpaulino** [comment]
@jburman thanks for the feedback! Do you think having the response time beside the response status code would improve your situation?

**Comment by jburman** [comment]
Yea, if it were visible all the time that would be even better.
Thanks!

**Comment by dpaulino** [comment]
Great, thanks. I'll work on this soon!

**Comment by dpaulino** [comment]
@jburman what do you think about this? 
![image](https://user-images.githubusercontent.com/7649589/68523805-fd743480-0272-11ea-9100-d8c465fc0309.png)

**Comment by jburman** [comment]
Yea that looks good to me. Just an idea, but I wonder how it would look with the status code slightly larger and the response time text reduced size under it?

**Comment by dpaulino** [comment]
Oh oops I may have accidentally deleted my previous message. That's a good idea, I'll give it a try!

**Comment by dpaulino** [comment]
Now available in 3.1.8. Let me know what you think

**Comment by jburman** [comment]
Yea that looks great - thanks for adding that in.

**Comment by dpaulino** [comment]
Just wanted to say thanks once again for bringing this to my attention. Since the launch of 3.1.8, I've already received several positive reactions to adding the response time beside the status code. I probably should have figured this out sooner, but sometimes it's hard to see things a different way when you're working on it everyday. I'm very glad you brought it up! Cheers
