### ISSUE TITLE
Status of project? Roadmap?

### ISSUE THREAD

**Issue by calloncampbell** [jenius-apps/nightingale-rest-api-client#252]
This is one of my favorite REST API client but I feel this project has become stale with little to no effort going on to improve the app. Are you able to provide a status update and possibly a roadmap for the future of Nightingale? Will we see this incorporate WinUI 3? Will this move out of UWP and into Win SDK?

**Comment by dpaulino** [comment]
I have a roadmap but admittedly time is scarce right now. The project is definitely not abandoned though. I'll share more when I can

**Comment by marcvanbreemen** [comment]
Really hope you're able to find some time to pick up development as I can't think of an other _native_ Windows app for testing API's that is of this quality.

**Comment by marcvanbreemen** [comment]
I know the feeling ;). Still I personally try to find some time to work on it in my spare time, because it's so fun to work on those projects. Once I succeeded to drag me from the couch to the Mac, and start typing, I'm on fire .... :)

**Comment by paule96** [comment]
Hi @dpaulino,

nightingale is still one of my most used apps even if some stuff doesn't work or need to be improved. Because the UI is hidden away, I was thinking if it would be possible to use the https://github.com/jenius-apps/nightingale-core in a new client UI that is pure open source. 

The question is, would this be a solution to remove you as a single resource that can improve stuff. I understand that the current UI must stay closed source. But I would be open to try it and write just in the open a new UI.

And if we can maybe find 3 to 4 people more that want to maintain and contribute to it, we can maybe improve fast.

**Comment by michael-hawker** [comment]
Congrats on open sourcing! Seems like roadmap in readme is pretty clear, can probably close this issue now?

**Comment by dpaulino** [comment]
yep :)
