### ISSUE TITLE
Bug: Moving requests around makes sometimes the app crash

### ISSUE THREAD

**Issue by lordkyuusei** [jenius-apps/nightingale-rest-api-client#39]
Hi Daniel!

I found a bug (and another on that may be related (or may not)). Please, take a look:
![Nightingale-REST-API-Client-2020-01-22-12-36-13](https://user-images.githubusercontent.com/18118930/72891293-3b321680-3d14-11ea-9d13-98c7d6286977.gif)

 - Despite the fact i'm not (yet) a premium user, i'm able to import collections of 5+ items.
 - When I try to add a new request to this collection, it fires an error "Please buy premium to do so", hover I can move requests inside. Then, when I move it around, sometimes it works, and sometimes, the app crash. Due to the fact i'm not premium? (or it's related to the fact it's scrolling in the same time?)

_Note: it's pretty hard to see it, but it crashed. You can notice because the mouse, for a few moment, loads then everything stops because I recorded it using windows 10 game bar_

Thanks!

**Comment by dpaulino** [comment]
Thanks for creating an issue! 

It was always my intention to let people import a collection with more than 5 items even without Premium. I want to encourage people to use Nightingale with the data that they had in other apps.

However, the purposefully remains if you try to add new items into that imported collection. There may be a bug here with the drag and drop. You shouldn't be able to drag an item into a collection if that exceeds the premium limitation. I'll investigate this soon.

**Comment by dpaulino** [comment]
I did some investigations. It looks like this is caused by a limitation in the TreeView control from [WinUI](https://github.com/microsoft/microsoft-ui-xaml) library. There is a small edge case where if you drop a request between two items really fast, a crash occurs. 

I have ideas on fixing this, but it will require some major structural changes that will be coming for Nightingale vNext.

So to be completely transparent, it will unfortunately take a while for this edge case bug to be fixed. For now, if you drop items slowly (wait for the 🚫 or ↗ icon to show up), you should avoid the crash. I'll make sure this bug is a priority for Nightingale vNext

**Comment by lordkyuusei** [comment]
No worries, I'll be more cautious in the future, good job! :)

**Comment by dpaulino** [comment]
Issue has been fixed, but it might still take a while to be released. Stay tuned!

**Comment by dpaulino** [comment]
Improvements have been deployed. Let me know what you think. If you see further problems, feel free to create a new issue!
