### ISSUE TITLE
request with a document file in form-data results in Exception 

### ISSUE THREAD

**Issue by niteshrestha** [jenius-apps/nightingale-rest-api-client#96]
## Brief summary of the bug
Cannot send a request with file in form-data.

## What you expect to happen
I expect 200 OK with JSON response
![image](https://user-images.githubusercontent.com/4751915/89514242-53bbd700-d7f5-11ea-849d-2083fb1a908c.png)

## What actually happens
Trying to send a request with file in form-data results in an exception below
![image](https://user-images.githubusercontent.com/4751915/89514419-8bc31a00-d7f5-11ea-9c28-916e0770a733.png)

## Reproduction steps
Send POST request to https://nightingalerestclienttest20200806144438.azurewebsites.net/api/Document/Parse with form-data of type file in body

**Comment by dpaulino** [comment]
Thanks @niteshrestha I will look into this soon. Sorry again for the trouble

**Comment by dpaulino** [comment]
@niteshrestha I just tried your repro steps with a json file and my POST seemed to succeed:
![image](https://user-images.githubusercontent.com/7649589/89603379-da84aa00-d81d-11ea-8525-a60f9bef5e3e.png)

What Content-Type are you using there? It's cutoff so I can't see the entire thing. I wonder if that makes a difference

**Comment by niteshrestha** [comment]
@dpaulino I was sending a Microsoft Word Document with Content-Type application/vnd.openxmlformats-officedocument.wordprocessingml.document
I have attached a sample document if needed 
[PaserTest.docx](https://github.com/jenius-apps/nightingale-rest-api-client/files/5039084/PaserTest.docx)

**Comment by dpaulino** [comment]
@niteshrestha Thanks for that. I can reproduce this now. 
![image](https://user-images.githubusercontent.com/7649589/89604436-1fa9db80-d820-11ea-9475-3d151922ac72.png)

**Comment by dpaulino** [comment]
I set up a local ASP.NET core server that will receive the file. Looks like the server receives the file properly:
![image](https://user-images.githubusercontent.com/7649589/89605953-b035eb00-d823-11ea-96db-81769a202ab7.png)

How are you determining if the file was received?

**Comment by niteshrestha** [comment]
Here is how I am doing
![image](https://user-images.githubusercontent.com/4751915/89607185-9df29600-d891-11ea-8d56-6a2b9ca18366.png)

**Comment by niteshrestha** [comment]
@dpaulino I have made a repo with the code if it help. I can't seem to hit a breakpoint too. https://github.com/niteshrestha/NightingaleRESTClientTest

**Comment by dpaulino** [comment]
Thanks for the sample repo. I found the bug, but it's not what it seems.

There's nothing wrong with Nightingale's ability to send a file. See here that I was able to take your sample repo and it received the docx file just fine:
![image](https://user-images.githubusercontent.com/7649589/89608772-e1fe8000-d82a-11ea-9cf1-c4a64e9c46e0.png)

The bug is that Nightingale does not change the "form data" list when you change between tabs. For example, try this:
- For reproducibility purposes reset Nightingale's tab state like this: close all tabs > save workspace > close nightingale > launch nightingale
- Open new tab > open body section > switch to form data > populate one row of form data
- Open another new tab > navigate to its form data list 
- You'll see this second tab's form data list is the same as the previous tab instead of being empty

I have a feeling that the form data list that you're "seeing" on your screen is not actually the form data list that's being sent.

**Comment by dpaulino** [comment]
I'll fix this asap

**Comment by niteshrestha** [comment]
@dpaulino can confirm I was able to get the response as expected when starting from scratch. Also I had noticed previously that when I switched to body and selected form-data in different tab it was populated with the file already there. 
Thank you for looking into it.

**Comment by dpaulino** [comment]
Good to hear you were able to confirm the bug and the workaround.

I just fixed it btw. The updated package will be submitted to the store as soon as it finishes compiling. Thanks very much for your help troubleshooting this issue!

**Comment by niteshrestha** [comment]
Thank you for your quick response. 👍

**Comment by dpaulino** [comment]
Now available in the store
